services:
  - type: web
    name: telegram-psychologist-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: WEBHOOK_URL
        fromService:
          type: web
          name: telegram-psychologist-bot
          property: url
